namespace Api.Common.Base {

    public enum BaseRole {

        ADMIN,

        ADD_MATERIA,
        EDIT_MATERIA,
        DISABLE_MATERIA,
        DETAIL_MATERIA,
        LIST_MATERIA,

        ADD_USUARIO,
        EDIT_USUARIO,
        DISABLE_USUARIO,
        DETAIL_USUARIO,
        LIST_USUARIO,

        ADD_CURSO,
        EDIT_CURSO,
        DISABLE_CURSO,
        DETAIL_CURSO,
        LIST_CURSO,

        ADD_CATEGORIA_PROFISSIONAL,
        EDIT_CATEGORIA_PROFISSIONAL,
        DISABLE_CATEGORIA_PROFISSIONAL,
        DETAIL_CATEGORIA_PROFISSIONAL,
        LIST_CATEGORIA_PROFISSIONAL,

        ADD_INSTITUICAO,
        EDIT_INSTITUICAO,
        DISABLE_INSTITUICAO,
        DETAIL_INSTITUICAO,
        LIST_INSTITUICAO,
        OWNER_INSTITUICAO,

        ADD_INSTITUICAO_CURSO,
        EDIT_INSTITUICAO_CURSO,
        DISABLE_INSTITUICAO_CURSO,
        DETAIL_INSTITUICAO_CURSO,
        LIST_INSTITUICAO_CURSO,

        ADD_INSTITUICAO_CURSO_OCORRENCIA,
        EDIT_INSTITUICAO_CURSO_OCORRENCIA,
        DISABLE_INSTITUICAO_CURSO_OCORRENCIA,
        DETAIL_INSTITUICAO_CURSO_OCORRENCIA,
        LIST_INSTITUICAO_CURSO_OCORRENCIA,

        EDIT_INSTITUICAO_CURSO_OCORRENCIA_NOTA,
        EDIT_INSTITUICAO_CURSO_OCORRENCIA_FALTA

    }

}