namespace Api.InstituicaoApi {

    public static class InstituicaoRole {

        public static readonly string OWNER_INSTITUICAO = "OWNER_INSTITUICAO";

        public static readonly string ADD_INSTITUICAO_CURSO = "ADD_INSTITUICAO_CURSO";
        public static readonly string EDIT_INSTITUICAO_CURSO = "EDIT_INSTITUICAO_CURSO";
        public static readonly string DISABLE_INSTITUICAO_CURSO = "DISABLE_INSTITUICAO_CURSO";
        public static readonly string DETAIL_INSTITUICAO_CURSO = "DETAIL_INSTITUICAO_CURSO";
        public static readonly string LIST_INSTITUICAO_CURSO = "LIST_INSTITUICAO_CURSO";

        public static readonly string ADD_INSTITUICAO_COLABORADOR = "ADD_INSTITUICAO_COLABORADOR";
        public static readonly string EDIT_INSTITUICAO_COLABORADOR = "EDIT_INSTITUICAO_COLABORADOR";
        public static readonly string DISABLE_INSTITUICAO_COLABORADOR = "DISABLE_INSTITUICAO_COLABORADOR";
        public static readonly string DETAIL_INSTITUICAO_COLABORADOR = "DETAIL_INSTITUICAO_COLABORADOR";
        public static readonly string LIST_INSTITUICAO_COLABORADOR = "LIST_INSTITUICAO_COLABORADOR";

        public static readonly string ADD_INSTITUICAO_COLABORADOR_PERFIL = "ADD_INSTITUICAO_COLABORADOR_PERFIL";
        public static readonly string EDIT_INSTITUICAO_COLABORADOR_PERFIL = "EDIT_INSTITUICAO_COLABORADOR_PERFIL";
        public static readonly string DISABLE_INSTITUICAO_COLABORADOR_PERFIL = "DISABLE_INSTITUICAO_COLABORADOR_PERFIL";
        public static readonly string DETAIL_INSTITUICAO_COLABORADOR_PERFIL = "DETAIL_INSTITUICAO_COLABORADOR_PERFIL";
        public static readonly string LIST_INSTITUICAO_COLABORADOR_PERFIL = "LIST_INSTITUICAO_COLABORADOR_PERFIL";

        public static readonly string ADD_INSTITUICAO_CURSO_OCORRENCIA = "ADD_INSTITUICAO_CURSO_OCORRENCIA";
        public static readonly string EDIT_INSTITUICAO_CURSO_OCORRENCIA = "EDIT_INSTITUICAO_CURSO_OCORRENCIA";
        public static readonly string DISABLE_INSTITUICAO_CURSO_OCORRENCIA = "DISABLE_INSTITUICAO_CURSO_OCORRENCIA";
        public static readonly string DETAIL_INSTITUICAO_CURSO_OCORRENCIA = "DETAIL_INSTITUICAO_CURSO_OCORRENCIA";
        public static readonly string LIST_INSTITUICAO_CURSO_OCORRENCIA = "LIST_INSTITUICAO_CURSO_OCORRENCIA";

        public static readonly string EDIT_INSTITUICAO_CURSO_OCORRENCIA_NOTA = "EDIT_INSTITUICAO_CURSO_OCORRENCIA_NOTA";
        public static readonly string EDIT_INSTITUICAO_CURSO_OCORRENCIA_FALTA = "EDIT_INSTITUICAO_CURSO_OCORRENCIA_FALTA";

    }

}